"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { PublicUser } from "../auth/types";
import { approvedExpenseTotal, pendingReimbursementTotal, reimbursementPending, reimbursementTotal, type SupervisorExpenseRow, type SupervisorExpenseStatus } from "../supervisor-expenses";

const inr = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const fmt = (n: number) => inr.format(n || 0);
const date = (value: string) => value ? new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "—";
type DashboardData = { expenses: SupervisorExpenseRow[]; orders: Array<{ id: string; orderNo: string; title: string; contractValue: number }>; payments: Array<{ id: string; orderId: string; personId: string; direction: string; amount: number; paymentDate: string; reference: string; notes: string }>; supervisorId: string; supervisorName: string };
type Detail = "total" | "person" | "order" | "supervisor" | "pending" | null;
function Status({ value }: { value: SupervisorExpenseStatus }) { const tone = value === "Approved" ? "success" : value === "Disapproved" ? "danger" : "warning"; return <span className={`status ${tone}`}>{value}</span>; }
export default function SupervisorExpenseDashboard({ user }: { user: PublicUser }) {
  const [data, setData] = useState<DashboardData>({ expenses: [], orders: [], payments: [], supervisorId: "", supervisorName: "" });
  const [loading, setLoading] = useState(true); const [detail, setDetail] = useState<Detail>(null); const [toast, setToast] = useState(""); const [working, setWorking] = useState(""); const [search, setSearch] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/expense-approvals", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to load expense dashboard"); setData(body); } catch (error) { setToast(error instanceof Error ? error.message : "Unable to load expense dashboard"); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 3500); return () => window.clearTimeout(timer); }, [toast]);
  const visible = useMemo(() => data.expenses.filter((expense) => `${expense.orderNo} ${expense.orderTitle} ${expense.supervisorName} ${expense.category} ${expense.description}`.toLowerCase().includes(search.toLowerCase())), [data.expenses, search]);
  const approved = approvedExpenseTotal(visible); const reimbursed = reimbursementTotal(visible); const pending = pendingReimbursementTotal(visible); const approvalPending = visible.filter((expense) => expense.status === "Pending approval").reduce((sum, expense) => sum + expense.amount, 0);
  const personRows = useMemo(() => { const map = new Map<string, { id: string; name: string; amount: number; pending: number; count: number }>(); visible.forEach((expense) => { const current = map.get(expense.supervisorId) || { id: expense.supervisorId, name: expense.supervisorName || "Unassigned", amount: 0, pending: 0, count: 0 }; current.amount += expense.status === "Approved" ? expense.amount : 0; current.pending += expense.status === "Approved" ? reimbursementPending(expense.amount, expense.reimbursedAmount) : 0; current.count += 1; map.set(expense.supervisorId, current); }); return [...map.values()].sort((a, b) => b.amount - a.amount); }, [visible]);
  const orderRows = useMemo(() => { const map = new Map<string, { id: string; orderNo: string; title: string; amount: number; pending: number; count: number }>(); visible.forEach((expense) => { const current = map.get(expense.orderId) || { id: expense.orderId, orderNo: expense.orderNo, title: expense.orderTitle, amount: 0, pending: 0, count: 0 }; current.amount += expense.status === "Approved" ? expense.amount : 0; current.pending += expense.status === "Approved" ? reimbursementPending(expense.amount, expense.reimbursedAmount) : 0; current.count += 1; map.set(expense.orderId, current); }); return [...map.values()].sort((a, b) => b.amount - a.amount); }, [visible]);
  const action = async (id: string, type: "approve" | "disapprove" | "reimburse") => { setWorking(`${type}:${id}`); try { const expense = data.expenses.find((row) => row.id === id); const amount = type === "reimburse" ? reimbursementPending(expense?.amount || 0, expense?.reimbursedAmount || 0) : undefined; if (type === "disapprove" && !window.confirm("Disapprove this supervisor expense? It will not count toward approved order cost or reimbursement.")) return; if (type === "reimburse" && (!amount || !window.confirm(`Record reimbursement of ${fmt(amount)} to this supervisor?`))) return; const response = await fetch("/api/expense-approvals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: type, expenseId: id, amount }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to update expense"); setToast(type === "approve" ? "Expense approved" : type === "disapprove" ? "Expense disapproved" : "Reimbursement recorded"); await load(); } catch (error) { setToast(error instanceof Error ? error.message : "Unable to update expense"); } finally { setWorking(""); } };
  const detailTitle = detail === "total" ? "All expense records" : detail === "person" ? "Person-wise expense" : detail === "order" ? "Order-wise expense" : detail === "supervisor" ? "Supervisor reimbursement" : "Pending reimbursement";
  const detailRows = detail === "person" ? personRows.map((row) => ({ id: row.id, title: row.name, meta: `${row.count} expense records · ${fmt(row.pending)} pending`, amount: row.amount })) : detail === "order" ? orderRows.map((row) => ({ id: row.id, title: `${row.orderNo}${row.title ? ` · ${row.title}` : ""}`, meta: `${row.count} expense records · ${fmt(row.pending)} reimbursement pending`, amount: row.amount })) : visible.map((row) => ({ id: row.id, title: `${row.orderNo} · ${row.supervisorName}`, meta: `${date(row.expenseDate)} · ${row.category} · ${row.status}`, amount: row.status === "Approved" ? reimbursementPending(row.amount, row.reimbursedAmount) : row.amount }));
  if (loading) return <div className="loading-screen"><div className="spinner" /><p>Loading expense command centre…</p></div>;
  return <div className="expense-command-centre">
    <div className="expense-dashboard-head"><div><span className="overline">{user.role === "admin" ? "Administrator workspace" : "Supervisor reimbursement workspace"}</span><h2>{user.role === "admin" ? "Expense command centre" : "My expense dashboard"}</h2><p>{user.role === "admin" ? "Review, approve and reimburse every supervisor expense from one place." : "Track what you have spent, what is approved, and what is still awaiting reimbursement."}</p></div><label className="global-search expense-search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order, supervisor or category" /></label></div>
    <div className="expense-kpi-grid"><button className="expense-kpi expense-kpi-primary" onClick={() => setDetail("total")}><span>Total expenses</span><strong>{fmt(visible.reduce((sum, row) => sum + row.amount, 0))}</strong><small>{visible.length} records · click to inspect</small></button><button className="expense-kpi" onClick={() => setDetail("person")}><span>Person-wise expense</span><strong>{fmt(approved)}</strong><small>{personRows.length} people · approved cost</small></button><button className="expense-kpi" onClick={() => setDetail("order")}><span>Order-wise expense</span><strong>{fmt(approved)}</strong><small>{orderRows.length} orders · approved cost</small></button><button className="expense-kpi" onClick={() => setDetail("pending")}><span>Pending reimbursement</span><strong>{fmt(pending)}</strong><small>Already paid by supervisors</small></button><button className="expense-kpi" onClick={() => setDetail("supervisor")}><span>Supervisor reimbursement</span><strong>{fmt(reimbursed)}</strong><small>Recorded as paid in history</small></button></div>
    {user.role === "admin" && <div className="expense-approval-banner"><div><span className="overline">Approval queue</span><strong>{fmt(approvalPending)}</strong><p>Supervisor expenses waiting for your decision</p></div><button className="btn btn-primary" onClick={() => setDetail("total")}>Open approval queue</button></div>}
    <div className="expense-overview-grid"><article className="panel expense-breakdown-panel"><div className="panel-head"><div><span className="overline">Person-wise</span><h3>Who spent what</h3></div><button className="link-btn" onClick={() => setDetail("person")}>View all →</button></div><div className="expense-breakdown-list">{personRows.slice(0, 6).map((row) => <button className="expense-breakdown-row expense-click-row" key={row.id} onClick={() => setDetail("person")}><div><strong>{row.name}</strong><span>{row.count} records · {fmt(row.pending)} pending</span></div><strong>{fmt(row.amount)}</strong><i><b style={{ width: `${Math.min(100, (row.amount / Math.max(approved, 1)) * 100)}%` }} /></i></button>)}{!personRows.length && <div className="mini-empty">No supervisor expenses yet.</div>}</div></article><article className="panel expense-breakdown-panel"><div className="panel-head"><div><span className="overline">Order-wise</span><h3>Cost added to orders</h3></div><button className="link-btn" onClick={() => setDetail("order")}>View all →</button></div><div className="expense-breakdown-list">{orderRows.slice(0, 6).map((row) => <button className="expense-breakdown-row expense-click-row" key={row.id} onClick={() => setDetail("order")}><div><strong>{row.orderNo}</strong><span>{row.title || "Order"} · {fmt(row.pending)} pending</span></div><strong>{fmt(row.amount)}</strong><i><b style={{ width: `${Math.min(100, (row.amount / Math.max(approved, 1)) * 100)}%` }} /></i></button>)}{!orderRows.length && <div className="mini-empty">No approved order expenses yet.</div>}</div></article></div>
    <article className="panel expense-history-panel"><div className="panel-head"><div><span className="overline">Payment history</span><h3>Supervisor reimbursements</h3></div><button className="link-btn" onClick={() => setDetail("pending")}>Pending →</button></div><div className="table-wrap"><table className="expense-table"><thead><tr><th>Date</th><th>Order</th><th>Supervisor</th><th>Expense</th><th>Status</th><th>Reimbursed</th><th>Pending</th><th /></tr></thead><tbody>{visible.slice(0, 20).map((row) => { const pendingAmount = reimbursementPending(row.amount, row.reimbursedAmount); return <tr key={row.id}><td>{date(row.expenseDate)}</td><td><strong>{row.orderNo}</strong><small>{row.orderTitle}</small></td><td>{row.supervisorName || "—"}</td><td>{fmt(row.amount)}<small>{row.category}</small></td><td><Status value={row.status} /></td><td>{fmt(row.reimbursedAmount)}</td><td className={pendingAmount ? "negative" : "positive"}>{row.status === "Approved" ? fmt(pendingAmount) : "—"}</td><td className="table-actions">{user.role === "admin" && row.status === "Pending approval" && <><button className="btn btn-small btn-primary" disabled={working !== ""} onClick={() => void action(row.id, "approve")}>Approve</button><button className="btn btn-small btn-danger" disabled={working !== ""} onClick={() => void action(row.id, "disapprove")}>Disapprove</button></>}{(user.role === "admin" || user.role === "accountant") && row.status === "Approved" && pendingAmount > 0 && <button className="btn btn-small btn-primary" disabled={working !== ""} onClick={() => void action(row.id, "reimburse")}>Reimburse</button>}</td></tr>; })}</tbody></table></div>{!visible.length && <div className="mini-empty">No expense records match the current search.</div>}</article>
    {detail && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setDetail(null)}><aside className="customer-drawer expense-detail-drawer"><button className="modal-close" onClick={() => setDetail(null)} aria-label="Close">×</button><div className="transaction-head"><span className="order-no">Expense detail</span><h2>{detailTitle}</h2><p>Every amount is separated into approved cost, reimbursement and pending reimbursement.</p></div><div className="transaction-summary"><div><span>Approved cost</span><strong>{fmt(approved)}</strong></div><div><span>Reimbursed</span><strong className="positive">{fmt(reimbursed)}</strong></div><div><span>Pending</span><strong className="negative">{fmt(pending)}</strong></div></div><div className="drawer-section"><div className="transaction-list">{detailRows.map((row) => <div className="transaction-item" key={row.id}><span className="activity-icon">₹</span><div className="grow"><strong>{row.title}</strong><span>{row.meta}</span></div><strong>{fmt(row.amount)}</strong></div>)}{!detailRows.length && <div className="mini-empty">No records.</div>}</div></div></aside></div>}
    {toast && <div className="toast" role="status"><span>✓</span>{toast}</div>}
  </div>;
}
